# Generated by Django 2.2 on 2020-02-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_of_creation', models.DateTimeField(auto_now=True)),
                ('task', models.ManyToManyField(related_name='tags', to='task.Task')),
            ],
        ),
    ]
